// Generated by CoffeeScript 1.3.3

/*
Copyright (c) 2012 Ramesh Nair (hiddentao.com)

Permission is hereby granted, free of charge, to any person
obtaining a copy of this software and associated documentation
files (the "Software"), to deal in the Software without
restriction, including without limitation the rights to use,
copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following
conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.
*/


(function() {
  var DistinctBlock, cls, squel, _extend,
    __slice = [].slice,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  cls = {};

  _extend = function() {
    var dst, k, sources, src, v, _i, _len;
    dst = arguments[0], sources = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    if (sources) {
      for (_i = 0, _len = sources.length; _i < _len; _i++) {
        src = sources[_i];
        if (src) {
          for (k in src) {
            if (!__hasProp.call(src, k)) continue;
            v = src[k];
            dst[k] = v;
          }
        }
      }
    }
    return dst;
  };

  cls.DefaultQueryBuilderOptions = {
    autoQuoteTableNames: false,
    autoQuoteFieldNames: false,
    nameQuoteCharacter: '`',
    usingValuePlaceholders: false
  };

  cls.Cloneable = (function() {

    function Cloneable() {}

    Cloneable.prototype.clone = function() {
      var newInstance;
      newInstance = new this.constructor;
      return _extend(newInstance, JSON.parse(JSON.stringify(this)));
    };

    return Cloneable;

  })();

  cls.BaseBuilder = (function(_super) {

    __extends(BaseBuilder, _super);

    function BaseBuilder(options) {
      this.options = _extend({}, cls.DefaultQueryBuilderOptions, options);
    }

    BaseBuilder.prototype._getObjectClassName = function(obj) {
      var arr;
      if (obj && obj.constructor && obj.constructor.toString) {
        arr = obj.constructor.toString().match(/function\s*(\w+)/);
        if (arr && arr.length === 2) {
          return arr[1];
        }
      }
      return void 0;
    };

    BaseBuilder.prototype._sanitizeCondition = function(condition) {
      var c, t;
      t = typeof condition;
      c = this._getObjectClassName(condition);
      if ('cls.Expression' !== c && "string" !== t) {
        throw new Error("condition must be a string or cls.Expression instance");
      }
      if ('cls.Expression' === t || 'cls.Expression' === c) {
        condition = condition.toString();
      }
      return condition;
    };

    BaseBuilder.prototype._sanitizeName = function(value, type) {
      if ("string" !== typeof value) {
        throw new Error("" + type + " must be a string");
      }
      return value;
    };

    BaseBuilder.prototype._sanitizeField = function(item) {
      var sanitized;
      sanitized = this._sanitizeName(item, "field name");
      if (this.options.autoQuoteFieldNames) {
        return "" + this.options.nameQuoteCharacter + sanitized + this.options.nameQuoteCharacter;
      } else {
        return sanitized;
      }
    };

    BaseBuilder.prototype._sanitizeTable = function(item) {
      var sanitized;
      sanitized = this._sanitizeName(item, "table name");
      if (this.options.autoQuoteTableNames) {
        return "" + this.options.nameQuoteCharacter + sanitized + this.options.nameQuoteCharacter;
      } else {
        return sanitized;
      }
    };

    BaseBuilder.prototype._sanitizeAlias = function(item) {
      return this._sanitizeName(item, "alias");
    };

    BaseBuilder.prototype._sanitizeLimitOffset = function(value) {
      value = parseInt(value);
      if (0 > value || isNaN(value)) {
        throw new Error("limit/offset must be >=0");
      }
      return value;
    };

    BaseBuilder.prototype._sanitizeValue = function(item) {
      var t;
      t = typeof item;
      if (null !== item && "string" !== t && "number" !== t && "boolean" !== t) {
        throw new Error("field value must be a string, number, boolean or null");
      }
      return item;
    };

    BaseBuilder.prototype._formatValue = function(value) {
      if (null === value) {
        value = "NULL";
      } else if ("boolean" === typeof value) {
        value = value ? "TRUE" : "FALSE";
      } else if ("number" !== typeof value) {
        if (false === this.options.usingValuePlaceholders) {
          value = "'" + value + "'";
        }
      }
      return value;
    };

    return BaseBuilder;

  })(cls.Cloneable);

  cls.Expression = (function() {
    var _toString;

    Expression.prototype.tree = null;

    Expression.prototype.current = null;

    function Expression() {
      this.toString = __bind(this.toString, this);

      this.or = __bind(this.or, this);

      this.and = __bind(this.and, this);

      this.end = __bind(this.end, this);

      this.or_begin = __bind(this.or_begin, this);

      this.and_begin = __bind(this.and_begin, this);

      var _this = this;
      this.tree = {
        parent: null,
        nodes: []
      };
      this.current = this.tree;
      this._begin = function(op) {
        var new_tree;
        new_tree = {
          type: op,
          parent: _this.current,
          nodes: []
        };
        _this.current.nodes.push(new_tree);
        _this.current = _this.current.nodes[_this.current.nodes.length - 1];
        return _this;
      };
    }

    Expression.prototype.and_begin = function() {
      return this._begin('AND');
    };

    Expression.prototype.or_begin = function() {
      return this._begin('OR');
    };

    Expression.prototype.end = function() {
      if (!this.current.parent) {
        throw new Error("begin() needs to be called");
      }
      this.current = this.current.parent;
      return this;
    };

    Expression.prototype.and = function(expr) {
      if (!expr || "string" !== typeof expr) {
        throw new Error("expr must be a string");
      }
      this.current.nodes.push({
        type: 'AND',
        expr: expr
      });
      return this;
    };

    Expression.prototype.or = function(expr) {
      if (!expr || "string" !== typeof expr) {
        throw new Error("expr must be a string");
      }
      this.current.nodes.push({
        type: 'OR',
        expr: expr
      });
      return this;
    };

    Expression.prototype.toString = function() {
      if (null !== this.current.parent) {
        throw new Error("end() needs to be called");
      }
      return _toString(this.tree);
    };

    _toString = function(node) {
      var child, nodeStr, str, _i, _len, _ref;
      str = "";
      _ref = node.nodes;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        child = _ref[_i];
        if (child.expr != null) {
          nodeStr = child.expr;
        } else {
          nodeStr = _toString(child);
          if ("" !== nodeStr) {
            nodeStr = "(" + nodeStr + ")";
          }
        }
        if ("" !== nodeStr) {
          if ("" !== str) {
            str += " " + child.type + " ";
          }
          str += nodeStr;
        }
      }
      return str;
    };

    return Expression;

  })();

  cls.BuildingBlock = (function(_super) {

    __extends(BuildingBlock, _super);

    function BuildingBlock() {
      return BuildingBlock.__super__.constructor.apply(this, arguments);
    }

    BuildingBlock.prototype.exposedMethods = function() {
      var attr, ret, value;
      ret = {};
      for (attr in this) {
        if (!__hasProp.call(this, attr)) continue;
        value = this[attr];
        if (typeof value === "Function") {
          if (attr.charAt(0) !== '_' && attr !== 'buildStr') {
            ret[attr] = value;
          }
        }
      }
      return ret;
    };

    BuildingBlock.prototype.buildStr = function(queryBuilder) {
      return '';
    };

    return BuildingBlock;

  })(cls.BaseBuilder);

  cls.StringBlock = (function(_super) {

    __extends(StringBlock, _super);

    function StringBlock(options, str) {
      StringBlock.__super__.constructor.call(this, options);
      this.str = str;
    }

    StringBlock.prototype.buildStr = function(queryBuilder) {
      return this.str;
    };

    return StringBlock;

  })(cls.BuildingBlock);

  cls.FromTableBlock = (function(_super) {

    __extends(FromTableBlock, _super);

    function FromTableBlock(options) {
      FromTableBlock.__super__.constructor.call(this, options);
      this.froms = [];
    }

    FromTableBlock.prototype.from = function(table, alias) {
      if (alias == null) {
        alias = null;
      }
      table = this._sanitizeTable(table);
      if (alias) {
        alias = this._sanitizeAlias(alias);
      }
      return this.froms.push({
        name: table,
        alias: alias
      });
    };

    FromTableBlock.prototype.buildStr = function(queryBuilder) {
      var table, tables, _i, _len, _ref;
      if (0 >= this.froms.length) {
        throw new Error("from() needs to be called");
      }
      tables = "";
      _ref = this.froms;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        table = _ref[_i];
        if ("" !== tables) {
          tables += ", ";
        }
        tables += table.name;
        if (table.alias) {
          tables += " `" + table.alias + "`";
        }
      }
      return "FROM " + tables;
    };

    return FromTableBlock;

  })(cls.BuildingBlock);

  cls.UpdateTableBlock = (function(_super) {

    __extends(UpdateTableBlock, _super);

    function UpdateTableBlock(options) {
      UpdateTableBlock.__super__.constructor.call(this, options);
      this.tables = [];
    }

    UpdateTableBlock.prototype.table = function(table, alias) {
      if (alias == null) {
        alias = null;
      }
      table = this._sanitizeTable(table);
      if (alias) {
        alias = this._sanitizeAlias(alias);
      }
      return this.tables.push({
        name: table,
        alias: alias
      });
    };

    UpdateTableBlock.prototype.buildStr = function(queryBuilder) {
      var table, tables, _i, _len, _ref;
      if (0 >= this.tables.length) {
        throw new Error("table() needs to be called");
      }
      tables = "";
      _ref = this.tables;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        table = _ref[_i];
        if ("" !== tables) {
          tables += ", ";
        }
        tables += table.name;
        if (table.alias) {
          tables += " AS `" + table.alias + "`";
        }
      }
      return tables;
    };

    return UpdateTableBlock;

  })(cls.BuildingBlock);

  cls.IntoTableBlock = (function(_super) {

    __extends(IntoTableBlock, _super);

    function IntoTableBlock(options) {
      IntoTableBlock.__super__.constructor.call(this, options);
      this.table = null;
    }

    IntoTableBlock.prototype.table = function(table) {
      return table = this._sanitizeTable(table);
    };

    IntoTableBlock.prototype.buildStr = function(queryBuilder) {
      if (!this.table) {
        throw new Error("into() needs to be called");
      }
      return this.table;
    };

    return IntoTableBlock;

  })(cls.BuildingBlock);

  cls.GetFieldBlock = (function(_super) {

    __extends(GetFieldBlock, _super);

    function GetFieldBlock(options) {
      this.field = __bind(this.field, this);
      GetFieldBlock.__super__.constructor.call(this, options);
      this.fields = [];
    }

    GetFieldBlock.prototype.field = function(field, alias) {
      if (alias == null) {
        alias = null;
      }
      field = this._sanitizeField(field);
      if (alias) {
        alias = this._sanitizeAlias(alias);
      }
      return this.fields.push({
        name: field,
        alias: alias
      });
    };

    GetFieldBlock.prototype.buildStr = function(queryBuilder) {
      var field, fields, _i, _len, _ref;
      fields = "";
      _ref = this.fields;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        field = _ref[_i];
        if ("" !== fields) {
          fields += ", ";
        }
        fields += field.name;
        if (field.alias) {
          fields += " AS \"" + field.alias + "\"";
        }
      }
      if ("" === fields) {
        return "*";
      } else {
        return fields;
      }
    };

    return GetFieldBlock;

  })(cls.BuildingBlock);

  cls.SetFieldBlock = (function(_super) {

    __extends(SetFieldBlock, _super);

    function SetFieldBlock(options) {
      this.set = __bind(this.set, this);
      SetFieldBlock.__super__.constructor.call(this, options);
      this.fields = {};
    }

    SetFieldBlock.prototype.set = function(field, value) {
      field = this._sanitizeField(field);
      value = this._sanitizeValue(value);
      this.fields[field] = value;
      return this;
    };

    SetFieldBlock.prototype.buildStr = function(queryBuilder) {
      var field, fieldNames, fields, _i, _len;
      fieldNames = (function() {
        var _ref, _results;
        _ref = this.fields;
        _results = [];
        for (field in _ref) {
          if (!__hasProp.call(_ref, field)) continue;
          _results.push(field);
        }
        return _results;
      }).call(this);
      if (0 >= fieldNames.length) {
        throw new Error("set() needs to be called");
      }
      fields = "";
      for (_i = 0, _len = fieldNames.length; _i < _len; _i++) {
        field = fieldNames[_i];
        if ("" !== fields) {
          fields += ", ";
        }
        fields += "" + field + " = " + (this._formatValue(this.fields[field]));
      }
      return "SET " + fields;
    };

    return SetFieldBlock;

  })(cls.BuildingBlock);

  cls.InsertIntoFieldBlock = (function(_super) {

    __extends(InsertIntoFieldBlock, _super);

    function InsertIntoFieldBlock(options) {
      this.set = __bind(this.set, this);
      InsertIntoFieldBlock.__super__.constructor.call(this, options);
      this.fields = {};
    }

    InsertIntoFieldBlock.prototype.set = function(field, value) {
      field = this._sanitizeField(field);
      value = this._sanitizeValue(value);
      this.fields[field] = value;
      return this;
    };

    InsertIntoFieldBlock.prototype.buildStr = function(queryBuilder) {
      var field, fieldNames, fields, name, values, _i, _len;
      fieldNames = (function() {
        var _ref, _results;
        _ref = this.fields;
        _results = [];
        for (name in _ref) {
          if (!__hasProp.call(_ref, name)) continue;
          _results.push(name);
        }
        return _results;
      }).call(this);
      if (0 >= fieldNames.length) {
        throw new Error("set() needs to be called");
      }
      fields = "";
      values = "";
      for (_i = 0, _len = fieldNames.length; _i < _len; _i++) {
        field = fieldNames[_i];
        if ("" !== fields) {
          fields += ", ";
        }
        fields += field;
        if ("" !== values) {
          values += ", ";
        }
        values += this._formatValue(this.fields[field]);
      }
      return "(" + fields + ") VALUES (" + values + ")";
    };

    return InsertIntoFieldBlock;

  })(cls.BuildingBlock);

  DistinctBlock = (function(_super) {

    __extends(DistinctBlock, _super);

    function DistinctBlock(options) {
      DistinctBlock.__super__.constructor.call(this, options);
      this.use_distinct = false;
    }

    DistinctBlock.prototype.distinct = function() {
      return this.useDistinct = true;
    };

    DistinctBlock.prototype.buildStr = function(queryBuilder) {
      if (this.useDistinct) {
        return "DISTINCT";
      } else {
        return "";
      }
    };

    return DistinctBlock;

  })(cls.BuildingBlock);

  cls.GroupByBlock = (function(_super) {

    __extends(GroupByBlock, _super);

    function GroupByBlock(options) {
      this.group = __bind(this.group, this);
      GroupByBlock.__super__.constructor.call(this, options);
      this.groups = [];
    }

    GroupByBlock.prototype.group = function(field) {
      field = this._sanitizeField(field);
      return this.groups.push(field);
    };

    GroupByBlock.prototype.buildStr = function(queryBuilder) {
      var f, groups, _i, _len, _ref;
      groups = "";
      if (0 < this.groups.length) {
        _ref = this.groups;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          f = _ref[_i];
          if ("" !== groups) {
            groups += ", ";
          }
          groups += f;
        }
        groups = "GROUP BY " + groups;
      }
      return groups;
    };

    return GroupByBlock;

  })(cls.BuildingBlock);

  cls.OffsetBlock = (function(_super) {

    __extends(OffsetBlock, _super);

    function OffsetBlock(options) {
      this.offset = __bind(this.offset, this);
      OffsetBlock.__super__.constructor.call(this, options);
      this.offsets = null;
    }

    OffsetBlock.prototype.offset = function(start) {
      start = this._sanitizeLimitOffset(start);
      return this.offsets = start;
    };

    OffsetBlock.prototype.buildStr = function(queryBuilder) {
      if (this.offsets("OFFSET " + this.offsets)) {

      } else {
        return "";
      }
    };

    return OffsetBlock;

  })(cls.BuildingBlock);

  cls.WhereBlock = (function(_super) {

    __extends(WhereBlock, _super);

    function WhereBlock(options) {
      this.where = __bind(this.where, this);
      WhereBlock.__super__.constructor.call(this, options);
      this.wheres = [];
    }

    WhereBlock.prototype.where = function(condition) {
      condition = this._sanitizeCondition(condition);
      if ("" !== condition) {
        return this.wheres.push(condition);
      }
    };

    WhereBlock.prototype.buildStr = function(queryBuilder) {
      if (this.offsets("OFFSET " + this.offsets)) {

      } else {
        return "";
      }
    };

    return WhereBlock;

  })(cls.BuildingBlock);

  cls.OrderByBlock = (function(_super) {

    __extends(OrderByBlock, _super);

    function OrderByBlock(options) {
      this.order = __bind(this.order, this);
      OrderByBlock.__super__.constructor.call(this, options);
      this.orders = [];
    }

    OrderByBlock.prototype.order = function(field, asc) {
      if (asc == null) {
        asc = true;
      }
      field = this._sanitizeField(field);
      return this.orders.push({
        field: field,
        dir: asc ? "ASC" : "DESC"
      });
    };

    OrderByBlock.prototype.buildStr = function(queryBuilder) {
      var o, orders, _i, _len, _ref;
      if (0 < this.orders.length) {
        orders = "";
        _ref = this.orders;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          o = _ref[_i];
          if ("" !== orders) {
            orders += ", ";
          }
          orders += "" + o.field + " " + o.dir;
        }
        return "ORDER BY " + orders;
      } else {
        return "";
      }
    };

    return OrderByBlock;

  })(cls.BuildingBlock);

  cls.LimitBlock = (function(_super) {

    __extends(LimitBlock, _super);

    function LimitBlock(options) {
      this.limit = __bind(this.limit, this);
      LimitBlock.__super__.constructor.call(this, options);
      this.limits = null;
    }

    LimitBlock.prototype.limit = function(max) {
      max = this._sanitizeLimitOffset(max);
      return this.limits = max;
    };

    LimitBlock.prototype.buildStr = function(queryBuilder) {
      if (this.limits("LIMIT " + this.limits)) {

      } else {
        return "";
      }
    };

    return LimitBlock;

  })(cls.BuildingBlock);

  cls.JoinBlock = (function(_super) {

    __extends(JoinBlock, _super);

    function JoinBlock(options) {
      this.outer_join = __bind(this.outer_join, this);

      this.right_join = __bind(this.right_join, this);

      this.left_join = __bind(this.left_join, this);

      this.join = __bind(this.join, this);
      JoinBlock.__super__.constructor.call(this, options);
      this.joins = [];
    }

    JoinBlock.prototype.join = function(table, alias, condition, type) {
      if (type == null) {
        type = 'INNER';
      }
      table = this._sanitizeTable(table);
      if (alias) {
        alias = this._sanitizeAlias(alias);
      }
      if (condition) {
        condition = this._sanitizeCondition(condition);
      }
      this.joins.push({
        type: type,
        table: table,
        alias: alias,
        condition: condition
      });
      return this;
    };

    JoinBlock.prototype.left_join = function(table, alias, condition) {
      if (alias == null) {
        alias = null;
      }
      if (condition == null) {
        condition = null;
      }
      return this.join(table, alias, condition, 'LEFT');
    };

    JoinBlock.prototype.right_join = function(table, alias, condition) {
      if (alias == null) {
        alias = null;
      }
      if (condition == null) {
        condition = null;
      }
      return this.join(table, alias, condition, 'RIGHT');
    };

    JoinBlock.prototype.outer_join = function(table, alias, condition) {
      if (alias == null) {
        alias = null;
      }
      if (condition == null) {
        condition = null;
      }
      return this.join(table, alias, condition, 'OUTER');
    };

    JoinBlock.prototype.buildStr = function(queryBuilder) {
      var j, joins, _i, _len, _ref;
      joins = "";
      _ref = this.joins || [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        j = _ref[_i];
        joins += " " + j.type + " JOIN " + j.table;
        if (j.alias) {
          joins += " `" + j.alias + "`";
        }
        if (j.condition) {
          joins += " ON (" + j.condition + ")";
        }
      }
      return joins;
    };

    return JoinBlock;

  })(cls.BuildingBlock);

  cls.QueryBuilder = (function(_super) {

    __extends(QueryBuilder, _super);

    function QueryBuilder(blocks) {
      var block, methodBody, methodName, _fn, _i, _len, _ref, _ref1,
        _this = this;
      this.block = blocks;
      _ref = this.blocks;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        block = _ref[_i];
        _ref1 = block.exposedMethods();
        _fn = function(name, body) {
          return _this[name] = function() {
            body.apply(_this, arguments);
            return _this;
          };
        };
        for (methodName in _ref1) {
          if (!__hasProp.call(_ref1, methodName)) continue;
          methodBody = _ref1[methodName];
          if (this[methodName] != null) {
            throw new Error(_getObjectClassName(this) + ("already has a builder method called " + methodName));
          }
          _fn(methodName, methodBody);
        }
      }
      ({
        toString: function() {
          return ((function() {
            var _j, _len1, _ref2, _results;
            _ref2 = this.blocks;
            _results = [];
            for (_j = 0, _len1 = _ref2.length; _j < _len1; _j++) {
              block = _ref2[_j];
              _results.push(block.buildStr(this));
            }
            return _results;
          }).call(_this)).join(" ");
        }
      });
    }

    return QueryBuilder;

  })(cls.BaseBuilder);

  cls.Select = (function(_super) {

    __extends(Select, _super);

    function Select(options) {
      var blocks;
      blocks = [new cls.StringBlock(options, 'SELECT'), new cls.GetFieldBlock(options), new cls.FromTableBlock(options), new cls.JoinBlock(options), new cls.WhereBlock(options), new cls.GroupByBlock(options), new cls.OrderByBlock(options), new cls.LimitBlock(options), new cls.OffsetBlock(options)];
      Select.__super__.constructor.call(this, blocks);
    }

    return Select;

  })(cls.QueryBuilder);

  cls.Update = (function(_super) {

    __extends(Update, _super);

    function Update(options) {
      var blocks;
      blocks = [new cls.StringBlock(options, 'UPDATE'), new cls.UpdateTableBlock(options), new cls.SetFieldBlock(options), new cls.WhereBlock(options), new cls.OrderByBlock(options), new cls.LimitBlock(options)];
      Update.__super__.constructor.call(this, blocks);
    }

    return Update;

  })(cls.QueryBuilder);

  cls.Delete = (function(_super) {

    __extends(Delete, _super);

    function Delete(options) {
      var blocks;
      blocks = [new cls.StringBlock(options, 'DELETE'), new cls.FromTableBlock(options), new cls.JoinBlock(options), new cls.WhereBlock(options), new cls.OrderByBlock(options), new cls.LimitBlock(options)];
      Delete.__super__.constructor.call(this, blocks);
    }

    return Delete;

  })(cls.QueryBuilder);

  cls.Insert = (function(_super) {

    __extends(Insert, _super);

    function Insert(options) {
      var blocks;
      blocks = [new cls.StringBlock(options, 'INSERT'), new cls.IntoTableBlock(options), new cls.InsertIntoFieldBlock(options)];
      Insert.__super__.constructor.call(this, blocks);
    }

    return Insert;

  })(cls.BaseBuilder);

  squel = {
    expr: function() {
      return new cls.Expression;
    },
    select: function(options) {
      return new cls.Select(options);
    },
    update: function(options) {
      return new cls.Update(options);
    },
    insert: function(options) {
      return new cls.Insert(options);
    },
    "delete": function(options) {
      return new cls.Delete(options);
    }
  };

  squel.remove = squel["delete"];

  squel.classes = cls;

  if (typeof define !== "undefined" && define !== null ? define.amd : void 0) {
    define(function() {
      return squel;
    });
  } else if (typeof module !== "undefined" && module !== null ? module.exports : void 0) {
    module.export = squel;
  } else {
    if (typeof window !== "undefined" && window !== null) {
      window.squel = squel;
    }
  }

}).call(this);
